export const webRoutes = {
  home: "/",
  homeID: "/:id",
  login: "/login",
  forgotPassword: "/forgot-password",
  verifyOtp: "/verify-Otp",
  resetPassword: "/reset-password",
  logout: "/logout",
  flight_search: "/flight-search",
  flight_search_V2: "/flight-search-V2",

  flight_search_id: "/flight-search/:id",
  airticket: "/airticket",
  airticketDetails: "/airticket/:id",
  travelers: "/travelers/view-travels",
  editTravelers: "/travelers/view-travels/:id",
  addTraveler: "/travelers/add-travelers",
  transactionHistory: "/transaction-history",
  generalLedger: "/general-ledger",
  flight_details: "/flight-details/:id",
  deposit: "/deposit",
  instantDeposit: "/instantDeposit",
  myAccount: "/myAccount",
  test: "/test",
  about: "/about",
  issuedTicket: "/issuedTicket",
  viewIssuedTicket: "/issuedTicket/:id",
  paymentSuccess: "/ticket-issue/payment-success",
  paymentUnsuccess: "/ticket-issue/payment-unsuccess",
  bookingRequest: "/bookingRequest",
  bookingRequestDetails: "/bookingRequest/:id",
  users: "/users",
  myAgency: "/myAgency",
  createMyAgency: "/createMyAgency",
  myAgencyDetails: "/myAgencyDetails/:id",
};

export const B2CRoutes = {
  user: "b2c/user",
  ticket: "b2c/ticket",
  viewTicket: "b2c/ticket/:id",
  setting: "b2c/setting",
  customerSupport: "b2c/customer-support",
  createComplain: "b2c/customer-complain",
  detailsComplain: "b2c/details-complain",
  viewReturnTicket: "b2c/return-ticket/:id",
  report: "b2c/report",
  payment: "b2c/payment",

  bookingRequest: "b2c/bookingRequest",
  b2cBookingRequestDetails: "b2c/bookingRequestDetails/:id",
};
