export const bankArray = [
  { id: 1, name: 'AB Bank Ltd.', value: 'AB Bank Ltd.' },
  { id: 2, name: 'Agrani Bank', value: 'Agrani Bank' },
  {
    id: 3,
    name: 'Al-Arafah Islami Bank Ltd.',
    value: 'Al-Arafah Islami Bank Ltd.',
  },
  { id: 4, name: 'Ansar VDP Unnayan Bank', value: 'Ansar VDP Unnayan Bank' },
  { id: 5, name: 'BASIC Bank', value: 'BASIC Bank' },
  { id: 6, name: 'BRAC Bank Ltd.', value: 'BRAC Bank Ltd.' },
  {
    id: 7,
    name: 'Bangladesh Commerce Bank Ltd.',
    value: 'Bangladesh Commerce Bank Ltd.',
  },
  {
    id: 8,
    name: 'Bangladesh Development Bank',
    value: 'Bangladesh Development Bank',
  },
  { id: 9, name: 'Bangladesh Krishi Bank', value: 'Bangladesh Krishi Bank' },
  { id: 10, name: 'Bank Al-Falah', value: 'Bank Al-Falah' },
  { id: 11, name: 'Bank Asia Ltd.', value: 'Bank Asia Ltd.' },
  { id: 12, name: 'CITI Bank NA', value: 'CITI Bank NA' },
  {
    id: 13,
    name: 'Commercial Bank of Ceylon',
    value: 'Commercial Bank of Ceylon',
  },
  {
    id: 14,
    name: 'Community Bank Bangladesh Limited',
    value: 'Community Bank Bangladesh Limited',
  },
  { id: 15, name: 'Dhaka Bank Ltd.', value: 'Dhaka Bank Ltd.' },
  { id: 16, name: 'Dutch Bangla Bank Ltd.', value: 'Dutch Bangla Bank Ltd.' },
  { id: 17, name: 'EXIM Bank Ltd.', value: 'EXIM Bank Ltd.' },
  { id: 18, name: 'Eastern Bank Ltd.', value: 'Eastern Bank Ltd.' },
  {
    id: 19,
    name: 'First Security Islami Bank Ltd.',
    value: 'First Security Islami Bank Ltd.',
  },
  {
    id: 20,
    name: 'Global Islamic Bank Ltd.',
    value: 'Global Islamic Bank Ltd.',
  },
  { id: 21, name: 'Grameen Bank', value: 'Grameen Bank' },
  { id: 22, name: 'HSBC', value: 'HSBC' },
  { id: 23, name: 'Habib Bank Ltd.', value: 'Habib Bank Ltd.' },
  { id: 24, name: 'ICB Islamic Bank', value: 'ICB Islamic Bank' },
  { id: 25, name: 'IFIC Bank Ltd.', value: 'IFIC Bank Ltd.' },
  {
    id: 26,
    name: 'Islami Bank Bangladesh Ltd.',
    value: 'Islami Bank Bangladesh Ltd.',
  },
  { id: 27, name: 'Jamuna Bank Ltd.', value: 'Jamuna Bank Ltd.' },
  { id: 28, name: 'Janata Bank', value: 'Janata Bank' },
  { id: 29, name: 'Jubilee Bank', value: 'Jubilee Bank' },
  { id: 30, name: 'Karmashangosthan Bank', value: 'Karmashangosthan Bank' },
  { id: 31, name: 'Meghna Bank Ltd.', value: 'Meghna Bank Ltd.' },
  { id: 32, name: 'Mercantile Bank Ltd.', value: 'Mercantile Bank Ltd.' },
  { id: 33, name: 'Midland Bank Ltd.', value: 'Midland Bank Ltd.' },
  { id: 34, name: 'Modhumoti Bank Ltd.', value: 'Modhumoti Bank Ltd.' },
  { id: 35, name: 'Mutual Trust Bank Ltd.', value: 'Mutual Trust Bank Ltd.' },
  { id: 36, name: 'NCC Bank Ltd.', value: 'NCC Bank Ltd.' },
  { id: 37, name: 'NRB Bank Ltd.', value: 'NRB Bank Ltd.' },
  {
    id: 38,
    name: 'NRB Commercial Bank Ltd.',
    value: 'NRB Commercial Bank Ltd.',
  },
  { id: 39, name: 'National Bank Ltd.', value: 'National Bank Ltd.' },
  {
    id: 40,
    name: 'National Bank of Pakistan',
    value: 'National Bank of Pakistan',
  },
  { id: 41, name: 'One Bank Ltd.', value: 'One Bank Ltd.' },
  { id: 42, name: 'Padma Bank Ltd.', value: 'Padma Bank Ltd.' },
  { id: 43, name: 'Palli Sanchay Bank', value: 'Palli Sanchay Bank' },
  { id: 44, name: 'Premier Bank Ltd.', value: 'Premier Bank Ltd.' },
  { id: 45, name: 'Prime Bank Ltd.', value: 'Prime Bank Ltd.' },
  { id: 46, name: 'Pubali Bank Ltd.', value: 'Pubali Bank Ltd.' },
  {
    id: 47,
    name: 'Rajshahi Krishi Unnayan Bank',
    value: 'Rajshahi Krishi Unnayan Bank',
  },
  { id: 48, name: 'Rupali Bank', value: 'Rupali Bank' },
  { id: 49, name: 'SBAC Bank Ltd.', value: 'SBAC Bank Ltd.' },
  {
    id: 50,
    name: 'Shahjalal Islami Bank Ltd.',
    value: 'Shahjalal Islami Bank Ltd.',
  },
  { id: 51, name: 'Shimanto Bank Ltd.', value: 'Shimanto Bank Ltd.' },
  {
    id: 52,
    name: 'Social Islami Bank Ltd.',
    value: 'Social Islami Bank Ltd.',
  },
  { id: 53, name: 'Sonali Bank', value: 'Sonali Bank' },
  { id: 54, name: 'Southeast Bank Ltd.', value: 'Southeast Bank Ltd.' },
  { id: 55, name: 'Standard Bank Ltd.', value: 'Standard Bank Ltd.' },
  {
    id: 56,
    name: 'Standard Chartered Bank',
    value: 'Standard Chartered Bank',
  },
  { id: 57, name: 'State Bank of India', value: 'State Bank of India' },
  { id: 58, name: 'The City Bank Ltd.', value: 'The City Bank Ltd.' },
  { id: 59, name: 'Trust Bank Ltd.', value: 'Trust Bank Ltd.' },
  { id: 60, name: 'Union Bank Ltd.', value: 'Union Bank Ltd.' },
  {
    id: 61,
    name: 'United Commercial Bank Ltd.',
    value: 'United Commercial Bank Ltd.',
  },
  { id: 62, name: 'Uttara Bank Ltd.', value: 'Uttara Bank Ltd.' },
  { id: 63, name: 'Woori Bank Ltd.', value: 'Woori Bank Ltd.' },
];
